export const WEATHER_SET_STATUS = "WEATHER_SET_LOADING";
export const WEATHER_SET_DATA = "WEATHER_SET_DATA";
export const WEATHER_SEARCH_LOCATION_NAME = "WEATHER_SEARCH_LOCATION_NAME";
export const WEATHER_SEARCH_LOCATION_GPS = "WEATHER_SEARCH_LOCATION_GPS";
export const WEATHER_SEARCH_LOCATION_WOEID = "WEATHER_SEARCH_LOCATION_WOEID";